services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: carrot-market
      MYSQL_USER: carrot
      MYSQL_PASSWORD: market
    ports:
      - 13306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/init:/docker-entrypoint-initdb.d
