import SWRProvider from "@/components/swr-provider";
import { Inter } from "next/font/google";
import "./globals.css";
import { classnames } from "@/libs/client/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Carrot Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classnames(
          inter.className,
          "mx-auto max-w-sm bg-neutral-900 text-white",
        )}
      >
        <SWRProvider>
          <main>{children}</main>
        </SWRProvider>
      </body>
    </html>
  );
}
